name: Sonic Action

on:
  pull_request:
    branches:
    - main

jobs:
  sonic-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sonic action
        uses: arybolovlev/sonic-action@2c63cbfc7023d9db1f086ef66cc28b0a20b1874c
        with:
          pr-number: ${{ github.event.number }}
