name: Sonic Action

pull_request:
  branches:
  - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Containerized Build
        uses: arybolovlev/sonic-action@4e1c7858254664e06a7d397d13ce3e9f04c98e44
        with:
          pr-number: ${{ github.event.number }}
