name: Sonic Action

on:
  pull_request:
    branches:
    - main

jobs:
  sonic-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sonic action
        uses: arybolovlev/sonic-action@9e4d122f0eb60a60b1618ba95077010ccc2539ee
        with:
          pr-number: ${{ github.event.number }}
